- id: '1582352141441'
  alias: Sunset Notification
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  action:
  - data:
      message: Beautiful sunset!
    service: notify.sendmail
  - data:
      message: Beautiful sunset!
    service: persistent_notification.create
  - delay: 0:35
  - data:
      message: Oh wow you really missed something great.
    service: notify.notify
- id: '1582353421791'
  alias: Full Moon Notification
  description: ''
  trigger:
  - entity_id: sensor.moon
    platform: state
    to: full_moon
  condition:
  - after: '17:00'
    condition: time
  action:
  - data:
      message: Full moon tonight!
    service: notify.sendmail
  - data:
      message: Full moon tonight!
    service: persistent_notification.create
- id: rpi_power_issue
  alias: Power Problem Notification
  trigger:
  - above: '0'
    entity_id: sensor.rpi_power_status
    for: 0:05:00
    platform: numeric_state
    value_template: '{{ state.attributes.value }}'
  condition:
  action:
  - data:
      message: Raspberry Pi reported {{ states.sensor.rpi_power_status.state }}
      title: Power Supply Issue
    data_template:
      message: '{{ states.sensor.rpi_power_status.state }}.'
      title: Power Supply Issue
    service: notify.sendmail
- id: '1582970027924'
  alias: Purify Air
  description: ''
  trigger:
  - above: '95'
    entity_id: air_quality.ke_ting
    for: 0:01:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: fan.ke_ting
    state: 'Off'
  action:
  - data: {}
    entity_id: fan.ke_ting
    service: fan.turn_on
  - data:
      message: The air is too dirty! Turning fan on.
      title: Air Quality
    service: notify.sendmail
