- id: '1582352141440'
  alias: Home Music
  description: ''
  trigger:
  - entity_id: person.yuan_dongmei
    platform: state
    to: Honme
  - entity_id: person.yuan_dongmei
    platform: state
    to: Home
  condition: []
  action:
  - service: imac_music.shuffle
  - service: fan.turn_on
- id: '1582352141441'
  alias: Sunset Notification
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
  action:
  - data:
      message: Beautiful sunset!
    service: persistent_notification.create
  - delay: 0:35
  - data:
      message: Oh wow you really missed something great.
    service: notify.notify
- id: '1582353421791'
  alias: Full Moon Notification
  description: ''
  trigger:
  - entity_id: sensor.moon
    platform: state
    to: full_moon
  condition:
  - after: '17:00'
    condition: time
  action:
  - data:
      message: Full moon tonight!
    service: notify.notify
  - data:
      message: Full moon tonight!
    service: persistent_notification.create
- id: rpi_power_issue
  alias: Power Problem Notification
  trigger:
  - above: '0'
    entity_id: sensor.rpi_power_status
    for: 0:05:00
    platform: numeric_state
    value_template: '{{ state.attributes.value }}'
  condition:
  action:
  - data_template:
      message: '{{ states.sensor.rpi_power_status.state }}.'
      title: Power Supply Issue
    service: notify.notify
- id: '1582970027924'
  alias: Purify Air
  description: ''
  trigger:
  - above: '95'
    entity_id: air_quality.ke_ting
    for: 0:01:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: fan.ke_ting
    service: fan.turn_on
