# Configure a default setup of Home Assistant (frontend, api, etc)
automation: !include automations.yaml
cloud:
config:

dyson:
  username: !secret dyun
  password: !secret dypw
  language: CN
  devices:
    - device_id: !secret dyid
      device_ip: 192.168.1.111

frontend:
group: !include groups.yaml
history:

homeassistant:
  latitude: !secret lati
  longitude: !secret long
  elevation: !secret elev
  name: Home
  temperature_unit: C
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - !secret nw1
        - !secret nw2
        - !secret nw3
        - !secret nw4
    - type: homeassistant

http:
  base_url: "*:8123"

logbook:

logger:
  default: info

lovelace:
  mode: yaml

mobile_app:
map:

#neato:
#  username: !secret neun
#  password: !secret nepw
#  vendor: neato

person:
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
shopping_list:
ssdp:
sun:
system_health:

# Text to speech
tts:
  - platform: google_translate

updater:
  include_used_components: true

volvooncall:
  username: !secret vvun
  password: !secret vvpw
  region: cn
  mutable: false

zeroconf:
zone: !include zone.yaml
