# Configure a default setup of Home Assistant (frontend, api, etc)
automation: !include automations.yaml
cloud:
config:

dyson:
  username: !secret dyun
  password: !secret dypw
  language: CN

frontend:
group: !include groups.yaml

history:

homeassistant:
  latitude: !secret lati
  longitude: !secret long
  elevation: !secret elev
  name: Home
  temperature_unit: C
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - !secret nw1
        - !secret nw2
        - !secret nw3
        - !secret nw4

http:
  server_host: "*"

icloud:
  - username: !secret icun
    password: !secret icpw

logbook:

logger:
  default: info

lovelace:
  mode: yaml

map:
mobile_app:

#neato:
#  username: !secret neun
#  password: !secret nepw
#  vendor: neato

notify:
  - name: sendmail
    platform: smtp
    server: smtp.office365.com
    port: 587
    timeout: 15
    sender: !secret hmun
    encryption: starttls
    username: !secret hmun
    password: !secret hmpw
    recipient:
      - !secret hmun
    sender_name: Home Assistant

person:

recorder:
  db_url: "postgresql://@/hass"
  purge_keep_days: 2
  exclude:
    domains:
      - updater

script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
shopping_list:
ssdp:
sun:
system_health:

# Text to speech
tts:
  - platform: google_translate

updater:
  include_used_components: true

volvooncall:
  username: !secret vvun
  password: !secret vvpw
  region: cn
  mutable: false

weather:
zeroconf:
zone: !include zone.yaml
