
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  latitude: !secret lati
  longitude: !secret long
  elevation: !secret elev
  name: Home
  temperature_unit: C
  time_zone: Asia/Shanghai
  unit_system: metric
  customize: !include customize.yaml

logger:
  default: info

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: "*:8123"

#neato:
#  username: !secret neun
#  password: !secret nepw
#  vendor: neato

dyson:
  username: !secret dyun
  password: !secret dypw
  language: CN
  devices:
    - device_id: !secret dyid
      device_ip: 192.168.1.111

volvooncall:
  username: !secret vvun
  password: !secret vvpw
  region: cn

shopping_list:

# Text to speech
tts:
  - platform: google_translate

sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
