- platform: bme280
  name: Living Room
  i2c_address: 0x76
  monitored_conditions:
    - pressure
- platform: rpi_power
  text_state: true
- platform: shodan
  api_key: !secret shodanapi
  query: !secret shodanqry
- platform: sht31
  name: Living Room
  i2c_address: 0x44
  monitored_conditions:
    - temperature
    - humidity
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: load_1m
    - type: ipv6_address
      arg: wlan0
    - type: throughput_network_in
      arg: wlan0
    - type: throughput_network_out
      arg: wlan0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_use
    - type: last_boot
- platform: vcgencmd
- platform: moon
