- platform: attributes
  attribute: air_quality_index
  friendly_name: AQI
  icon: "mdi:cloud"
  entities:
    - air_quality.ke_ting
- platform: attributes
  attribute: nitrogen_dioxide
  friendly_name: "氮氧化物"
  unit_of_measurement: "μg/m³"
  icon: "mdi:cloud"
  entities:
    - air_quality.ke_ting
- platform: attributes
  attribute: particulate_matter_10
  friendly_name: "PM 10"
  unit_of_measurement: "μg/m³"
  icon: "mdi:cloud"
  entities:
    - air_quality.ke_ting
- platform: attributes
  attribute: particulate_matter_2_5
  friendly_name: "PM 2.5"
  unit_of_measurement: "μg/m³"
  icon: "mdi:cloud"
  entities:
    - air_quality.ke_ting
- platform: attributes
  attribute: volatile_organic_compounds
  friendly_name: "VOC"
  unit_of_measurement: "μg/m³"
  icon: "mdi:cloud"
  entities:
    - air_quality.ke_ting
- platform: bme280
  name: Living Room
  i2c_address: 0x76
  monitored_conditions:
    - pressure
- platform: rpi_power
  text_state: true
- platform: shodan
  api_key: !secret shodanapi
  query: !secret shodanqry
- platform: sht31
  name: Living Room
  i2c_address: 0x44
  monitored_conditions:
    - temperature
    - humidity
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: load_1m
    - type: ipv6_address
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_use
    - type: last_boot
- platform: vcgencmd
- platform: moon
