title: 家
views:
  - title: 设施
    path: system
    badges:
      - entity: person.zhang_maiyun
      - entity: person.yuan_dongmei
    cards:
      - title: Dyson
        type: entities
        show_header_toggle: false
        entities:
          - fan.ke_ting
          - air_quality.ke_ting
          - sensor.ke_ting_temperature
          - sensor.ke_ting_humidity
      - type: entities
        title: 系统状态
        entities:
          - entity: sensor.arm_temperature
          - entity: sensor.arm_voltage
          - entity: sensor.arm_frequency
          - entity: sensor.rpi_power_status
          - entity: sensor.load_1m
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.last_boot
          - entity: sensor.ipv6_address_eth0
          - entity: sensor.network_throughput_in_eth0
          - entity: sensor.network_throughput_out_eth0
        show_header_toggle: false
      - type: entities
        title: 车
        show_header_toggle: false
        entities:
          - entity: device_tracker.volvo_lvypd10d1lp142664
          - entity: binary_sensor.lvypd10d1lp142664_doors
          - entity: binary_sensor.lvypd10d1lp142664_windows
          - entity: binary_sensor.lvypd10d1lp142664_engine
          - entity: binary_sensor.lvypd10d1lp142664_bulbs
          - entity: binary_sensor.lvypd10d1lp142664_service
          - entity: sensor.lvypd10d1lp142664_fuel_amount
          - entity: sensor.lvypd10d1lp142664_last_trip
          - entity: sensor.lvypd10d1lp142664_range
          - entity: sensor.lvypd10d1lp142664_odometer
  - title: 情况
    path: state
    cards:
      - type: shopping-list
      - entity: weather.jia
        type: weather-forecast
      - type: entities
        title: Shodan
        show_header_toggle: false
        entities:
          - entity: sensor.shodan_sensor
      - type: entities
        entities:
          - entity: sun.sun
          - entity: sensor.moon
      - type: entities
        title: 空气质量
        entities:
          - entity: sensor.ke_ting_air_quality_index
          - entity: sensor.ke_ting_particulate_matter_10
          - entity: sensor.ke_ting_particulate_matter_2_5
          - entity: sensor.ke_ting_nitrogen_dioxide
          - entity: sensor.ke_ting_volatile_organic_compounds
        show_header_toggle: false
      - type: sensor
        entity: sensor.living_room_temperature
        graph: line
        name: 客厅温度
      - type: sensor
        entity: sensor.living_room_humidity
        graph: line
      - type: sensor
        entity: sensor.living_room_pressure
        graph: line
      #- type: entities
        #title: Scene
