title: Home
views:
  - title: Home
    path: default_view
    badges:
      - entity: person.zhang_maiyun
      - entity: sensor.battery_state
      - entity: sensor.battery_level
      - entity: sensor.iphone_battery_state
      - entity: sensor.myzs_apple_watch_battery_state
      - entity: person.yuan_dongmei
      - entity: sensor.battery_state_2
      - entity: sensor.battery_level_2
      - entity: sensor.zmys_iphone_battery_state
      - entity: sensor.yuan_dong_mei_de_ipad_battery_state
      - entity: sensor.mai_mai_de_ipad_battery_state
    cards:
      - type: shopping-list
      - type: entity-button
        entity: automation.home_music
        tap_action:
          action: call-service
          service: imac_music.shuffle
        hold_action:
          action: more-info
        icon: 'mdi:play'
        name: Shuffle
      - type: entity-button
        entity: automation.home_music
        tap_action:
          action: call-service
          service: imac_music.stop
        hold_action:
          action: more-info
        icon: 'mdi:stop'
        name: Stop
      - type: entities
        title: 空气质量
        entities:
          - entity: sensor.ke_ting_air_quality_index
          - entity: sensor.ke_ting_particulate_matter_10
          - entity: sensor.ke_ting_particulate_matter_2_5
          - entity: sensor.ke_ting_nitrogen_dioxide
          - entity: sensor.ke_ting_volatile_organic_compounds
        show_header_toggle: false
      - type: entities
        title: 系统状态
        entities:
          - entity: sensor.arm_temperature
          - entity: sensor.arm_voltage
          - entity: sensor.arm_frequency
          - entity: sensor.rpi_power_status
          - entity: sensor.load_1m
          - entity: sensor.processor_use
          - entity: sensor.memory_use_percent
          - entity: sensor.last_boot
          - entity: sensor.ipv6_address_eth0
          - entity: sensor.network_throughput_in_eth0
          - entity: sensor.network_throughput_out_eth0
        show_header_toggle: false
      - entity: weather.jia
        type: weather-forecast
      - title: Dyson
        type: entities
        show_header_toggle: false
        entities:
          - fan.ke_ting
          - air_quality.ke_ting
          - sensor.ke_ting_temperature
          - sensor.ke_ting_humidity
      - type: sensor
        entity: sensor.living_room_temperature
        graph: line
        name: 客厅温度
      - type: sensor
        entity: sensor.living_room_humidity
        graph: line
      - type: sensor
        entity: sensor.living_room_pressure
        graph: line
      - type: entities
        entities:
          - entity: sun.sun
          - entity: sensor.moon
      #- type: entities
        #title: Scene
      - type: entities
        title: Shodan
        show_header_toggle: false
        entities:
          - entity: sensor.shodan_sensor
      - type: entities
        title: 车
        show_header_toggle: false
        entities:
          - entity: device_tracker.volvo_lvypd10d1lp142664
          - entity: binary_sensor.lvypd10d1lp142664_doors
          - entity: binary_sensor.lvypd10d1lp142664_windows
          - entity: binary_sensor.lvypd10d1lp142664_engine
          - entity: binary_sensor.lvypd10d1lp142664_bulbs
          - entity: binary_sensor.lvypd10d1lp142664_service
          - entity: sensor.lvypd10d1lp142664_fuel_amount
          - entity: sensor.lvypd10d1lp142664_last_trip
          - entity: sensor.lvypd10d1lp142664_range
          - entity: sensor.lvypd10d1lp142664_odometer
