play:
  description: Starts playing the music.
  fields:
    queue_position:
      description: Position of the song in the queue to start playing from.
      example: '0'

shuffle:
  description: Starts playing from a random item.

stop:
  description: Stops playing.
